@startuml
title Login Page Flowchart
start
:display login page;
repeat
  :input username and password;
  if (credentials are valid?) then (yes)
    :logged in;
    if (user role is Teacher) then (yes)
      :display Teacher Dashboard;
      stop
    else (no)
      if (user role is Admin) then (yes)
        :display Admin Dashboard;
        stop
      endif
    endif
  else (no)
    :display error;
  endif
repeat while (true)
@enduml
